apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: api
          image: premier-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: APIFOOTBALL_KEY
              value: "45379e002ce9894ab347104d24165229"
            - name: NEWS_API_KEY
              value: "ab374a6cce8d4b8287ece795f4f71b1b"
            - name: SUPABASE_URL
              value: "http://192.168.1.24:8000"
            - name: SUPABASE_SERVICE_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE2NDE3NjkyMDAsImV4cCI6MTc5OTUzNTYwMH0.G_C6qYQLxXWnceCTF98pezfFnfI64TVi2GBziEiHHZQ"
            - name: NODE_ENV
              value: "production"
            - name: COOKIE_SECRET
              value: "ph_super_secret_key_2025_cambiame"
            - name: CORS_ORIGIN
              value: "https://app.zamer-o.com"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400