apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
  namespace: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
      - name: ml
        image: premier-ml:preprod
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 1.1.1.1
